### PR TITLE
Model Building

### PR DESCRIPTION
**Pull request by sharonibejih**
[Task: Model Building](https://github.com/HamoyeHQ/04-police-shootings/projects/1#card-46260896)
I have built the classification model for the task. Please review, and share your thoughts.

### CODE REVIEW

**Review by Jahfaith — APPROVED** [review]

**Review by Dwey125 — APPROVED** [review]
Approved...Well done Sharon.

**Comment by olaidejoseph** [comment]
Nice one Sharon.

**Review by olaidejoseph — APPROVED** [review]

**Review by Adeola23 — APPROVED** [review]
Really nice job !!!!

**Review by ForChune — APPROVED** [review]
Well done with the analysis, Sharon! Just an observation, I feel it would have been insightful if the profile of the suspects that were shot unjustly was provided. For instance, is there any commonality between all of them? Perhaps this question was answered by the other analyses.
Anyways, I'll be approving this to be merged. Well done once again!

**Pull request merged**
